### ISSUE TITLE
Crash when Bandicam hooks glfw + PyOpenGL applications

### ISSUE THREAD

**Issue by Zuzu-Typ** [glfw/glfw#1044]
When trying to use [Bandicam](https://www.bandicam.com/) to record a glfw (OpenGL) application it crashes after swapping buffers upon calling any OpenGL function with error 1280, which corresponds to GL_INVALID_ENUM:

``` Python
Traceback (most recent call last):
  File "D:\main.py", line 99, in <module>
    glClear(GL_COLOR_BUFFER_BIT)
  File "C:\Python36\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1280,
	description = b'Ungültiger Enumerant.',
	baseOperation = glClear,
	cArguments = (GL_COLOR_BUFFER_BIT,)
)
```

You can see what I mean, by [downloading a trial verson of Bandicam](https://www.bandicam.com/downloads/ing/) and any of your scripts or the following example (which is based on [this example](https://gist.github.com/deepankarsharma/3494203) and is using GLFW's official windows binaries glfw3.dll (x86, you might want to [download the x64 version](https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.bin.WIN64.zip) if you are using python 64 bit)): [glfw pyopengl example.zip](https://github.com/glfw/glfw/files/1146737/glfw.pyopengl.example.zip)
This script requires
- glfw
- PyOpenGL
- numpy

**Comment by Zuzu-Typ** [comment]
Here you can see the same example with pygame, where there is no crash.
[pygame pyopengl example.zip](https://github.com/glfw/glfw/files/1146793/pygame.pyopengl.example.zip)

**Comment by elmindreda** [comment]
I'm not sure how this would be caused by GLFW, which isn't directly involved in calls to `glClear`.

**Comment by elmindreda** [comment]
You say it's based on the linked example. Do you call any other OpenGL functions before the one that causes an error?

**Comment by elmindreda** [comment]
Do you have the C++ version available?

**Comment by Zuzu-Typ** [comment]
While I do not have a complete equivalent, this code doesn't vary too much from the python version.
[Debug.zip](https://github.com/glfw/glfw/files/1146997/Debug.zip)
(this code is entirely copied from [LearnOpenGL](https://learnopengl.com/code_viewer_gh.php?code=src/1.getting_started/2.1.hello_triangle/hello_triangle.cpp))

**Comment by Zuzu-Typ** [comment]
I've just ported the [aforementioned C++ code](https://learnopengl.com/code_viewer_gh.php?code=src/1.getting_started/2.1.hello_triangle/hello_triangle.cpp) to python.
Same issue, as expected.
``` Python
import glfw
import numpy
from OpenGL.arrays import ArrayDatatype
from OpenGL.GL import *
from OpenGL.GLU import *

__APPLE__ = False

# settings
SCR_WIDTH = 800
SCR_HEIGHT = 600

vertexShaderSource = """#version 330 core
layout (location = 0) in vec3 aPos;
void main()
{
   gl_Position = vec4(aPos.x, aPos.y, aPos.z, 1.0);
}"""
fragmentShaderSource = """#version 330 core
out vec4 FragColor;
void main()
{
   FragColor = vec4(1.0f, 0.5f, 0.2f, 1.0f);
}"""

# process all input: query GLFW whether relevant keys are pressed/released this frame and react accordingly
# ---------------------------------------------------------------------------------------------------------
def processInput(window):
    if (glfw.get_key(window, glfw.KEY_ESCAPE) == glfw.PRESS):
        glfw.set_window_should_close(window, True)

# glfw: whenever the window size changed (by OS or user resize) this callback function executes
# ---------------------------------------------------------------------------------------------
def framebuffer_size_callback(window, width, height):
    # make sure the viewport matches the new window dimensions; note that width and 
    # height will be significantly larger than specified on retina displays.
    glViewport(0, 0, width, height)

def main():
    # glfw: initialize and configure
    # ------------------------------
    glfw.init()
    glfw.window_hint(glfw.CONTEXT_VERSION_MAJOR, 3)
    glfw.window_hint(glfw.CONTEXT_VERSION_MINOR, 3)
    glfw.window_hint(glfw.OPENGL_PROFILE, glfw.OPENGL_CORE_PROFILE)

    if __APPLE__:
        glfw.window_hint(glfw.OPENGL_FORWARD_COMPAT, GL_TRUE) # uncomment this statement to fix compilation on OS X

    # glfw window creation
    # --------------------
    window = glfw.create_window(SCR_WIDTH, SCR_HEIGHT, "LearnOpenGL", None, None)
    if (window == None):
        print("Failed to create GLFW window")
        glfw.terminate()
        return -1
    glfw.make_context_current(window)
    glfw.set_framebuffer_size_callback(window, framebuffer_size_callback)


    # build and compile our shader program
    # ------------------------------------
    # vertex shader
    vertexShader = glCreateShader(GL_VERTEX_SHADER)
    glShaderSource(vertexShader, vertexShaderSource)
    glCompileShader(vertexShader)
    # check for shader compile errors
    
    if (not glGetShaderiv(vertexShader, GL_COMPILE_STATUS)):
        infoLog = glGetShaderInfoLog(vertexShader)
        print("ERROR::SHADER::VERTEX::COMPILATION_FAILED\n" + infoLog)
    # fragment shader
    fragmentShader = glCreateShader(GL_FRAGMENT_SHADER)
    glShaderSource(fragmentShader, fragmentShaderSource)
    glCompileShader(fragmentShader)
    # check for shader compile errors
    if (not glGetShaderiv(fragmentShader, GL_COMPILE_STATUS)):
        infoLog = glGetShaderInfoLog(fragmentShader)
        print("ERROR::SHADER::VERTEX::COMPILATION_FAILED\n" + infoLog)
    # link shaders
    shaderProgram = glCreateProgram()
    glAttachShader(shaderProgram, vertexShader)
    glAttachShader(shaderProgram, fragmentShader)
    glLinkProgram(shaderProgram)
    # check for linking errors
    if (not glGetProgramiv(shaderProgram, GL_LINK_STATUS)):
        infoLog = glGetProgramInfoLog(shaderProgram)
        print("ERROR::SHADER::PROGRAM::LINKING_FAILED\n" + infoLog)
    glDeleteShader(vertexShader)
    glDeleteShader(fragmentShader)

    # set up vertex data (and buffer(s)) and configure vertex attributes
    # ------------------------------------------------------------------
    vertices = numpy.array([
        -0.5, -0.5, 0.0, # left  
         0.5, -0.5, 0.0, # right 
         0.0,  0.5, 0.0  # top
        ], dtype=numpy.float32)
    
    VAO = glGenVertexArrays(1)
    VBO = glGenBuffers(1)
    # bind the Vertex Array Object first, then bind and set vertex buffer(s), and then configure vertex attributes(s).
    glBindVertexArray(VAO)

    glBindBuffer(GL_ARRAY_BUFFER, VBO)
    glBufferData(GL_ARRAY_BUFFER, ArrayDatatype.arrayByteCount(vertices), vertices, GL_STATIC_DRAW)

    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 12, None)
    glEnableVertexAttribArray(0)

    # note that this is allowed, the call to glVertexAttribPointer registered VBO as the vertex attribute's bound vertex buffer object so afterwards we can safely unbind
    glBindBuffer(GL_ARRAY_BUFFER, 0) 

    # You can unbind the VAO afterwards so other VAO calls won't accidentally modify this VAO, but this rarely happens. Modifying other
    # VAOs requires a call to glBindVertexArray anyways so we generally don't unbind VAOs (nor VBOs) when it's not directly necessary.
    glBindVertexArray(0)


    # uncomment this call to draw in wireframe polygons.
    #glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);

    # render loop
    # -----------
    while (not glfw.window_should_close(window)):
        # input
        # -----
        processInput(window)

        # render
        # ------
        glClearColor(0.2, 0.3, 0.3, 1.0)
        glClear(GL_COLOR_BUFFER_BIT)

        # draw our first triangle
        glUseProgram(shaderProgram)
        glBindVertexArray(VAO) # seeing as we only have a single VAO there's no need to bind it every time, but we'll do so to keep things a bit more organized
        glDrawArrays(GL_TRIANGLES, 0, 3)
        # glBindVertexArray(0); # no need to unbind it every time 
 
        # glfw: swap buffers and poll IO events (keys pressed/released, mouse moved etc.)
        # -------------------------------------------------------------------------------
        glfw.swap_buffers(window)
        glfw.poll_events()

    # optional: de-allocate all resources once they've outlived their purpose:
    # ------------------------------------------------------------------------
    print(VAO, VBO)
    glDeleteVertexArrays(1, (VAO,))
    glDeleteBuffers(1, (VBO,))

    # glfw: terminate, clearing all previously allocated GLFW resources.
    # ------------------------------------------------------------------
    glfw.terminate()
    return 0

main()
```

**Comment by elmindreda** [comment]
> Bandicam does not have any issues with the same basic script when written in C++, I thought it would be best to stop by here first.

I suspect this is the important bit. The Python binding you're using appears to check behind the scenes if any OpenGL errors have occurred and throws if one has. The C++ code does not do this, so the error is ignored.

I suspect Bandicam is causing the error when it hooks into the context, probably because it doesn't take enough care dealing with the core profile. Try changing your Python code to create a compatibility profile context and see if this changes anything.

**Comment by Zuzu-Typ** [comment]
You are apparently entirely correct.

If you use the compatibility profile, there is no error and at the same time, when you use the core profile in C++, you get a repeating error, when calling glGetError(), as soon as you let Bandicam hook your window.

That's also why pygame "doesn't have the issue", because it uses the compatibility profile.

I hope I didn't waste too much of your time. 
My dearest thanks to you.

I'm going to let Bandicam's developers know about this issue and I apologize for accusing you of causing it.

**Comment by elmindreda** [comment]
No worries!
