### ISSUE TITLE
Segfault during glfwDestroyWindow (Linux)

### ISSUE THREAD

**Issue by winduptoy** [glfw/glfw#1155]
**OS and version:** Arch Linux fully updated (2017/12/05)
**Release or commit:** glfw-3.2.1
**Error messages:** (none)
**CPU:** Intel Core i5-6200U
**GPU:** Intel HD Graphics 520
**mesa version:** 17.2.6-1
**xf86-video-intel version:** 1:2.99.917+800+g37a682aa-1
**Call stack:**
```
#0  0x00007ffe232574a0 in ?? ()
#1  0x00007f53af847a52 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#2  0x00007f53af7a746f in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#3  0x00007f53af6ad8d7 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#4  0x00007f53af6adb80 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#5  0x00007f53af6adbff in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#6  0x00007f53af686162 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#7  0x00007f53af6b069f in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#8  0x00007f53af5e4b1e in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#9  0x00007f53af940028 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#10 0x00007f53af904733 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#11 0x00007f53b532f871 in ?? () from /usr/lib/libGLX_mesa.so.0
#12 0x00007f53b52fffbb in ?? () from /usr/lib/libGLX_mesa.so.0
#13 0x000055f263d77a94 in destroyContextGLX ()
#14 0x000055f263d7417e in _glfwPlatformDestroyWindow ()
#15 0x000055f263d6b6df in glfwDestroyWindow ()
#16 0x000055f263d6739e in glfwTerminate ()
#17 0x000055f263d60cfe in main(argc=1, argv=0x7ffe232576a8)
```

The example above shows `glfwTerminate()` but I was able to reproduce the same segfault by calling `glfwDestroyWindow()` from my code as well.

Anyone run into this before?

**Comment by ghuser404** [comment]
#1146; try master.

**Comment by winduptoy** [comment]
Scratch that. This does not happen when I roll back my code to a previous commit. I must be smashing the stack or something.
