### ISSUE TITLE
Crashes on windows

### ISSUE THREAD

**Issue by bhperry** [glfw/glfw#1762]
Having issues running programs that use glfw on my Windows machine. Couldn't get it to build or run at all for a while, so I've been developing on win10 WSL. Randomly got it to run by cross-compiling from my WSL ubuntu environment, but now it's just not working again.

Ran `GOTRACEBACK=crash ./main.exe` to get the stack trace below, without that it just gives me errors like `runtime: unknown pc 0x21c75060000` and a mem dump.

Also, strangely, it frequently doesn't get a stack trace even with `GOTRACEBACK=crash`. Running the exact same command again just gets me the generic error and mem dump, and often freezes the terminal for a while.

Any help would be appreciated.

```
Exception 0xc0000005 0x0 0x7ffdd2bf2fff 0x2003c540000
PC=0x2003c540000
signal arrived during external code execution
runtime.cgocall(0xe50c00, 0xc00011dee0, 0x3fe0000000000000)
c:/go/src/runtime/cgocall.go:133 +0x55 fp=0xc00011deb0 sp=0xc00011de78 pc=0xce47d5
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwInit(0x3fd3d3d300000000)
_cgo_gotypes.go:1435 +0x50 fp=0xc00011dee0 sp=0xc00011deb0 pc=0xdf2bf0
github.com/go-gl/glfw/v3.3/glfw.Init(0xd27778, 0xe63600)
C:/Users/bhper/go/src/github.com/go-gl/glfw/v3.3/glfw/glfw.go:36 +0x29 fp=0xc00011df20 sp=0xc00011dee0 pc=0xdf5089
github.com/faiface/pixel/pixelgl.Run(0xed6028)
C:/Users/bhper/go/src/github.com/faiface/pixel/pixelgl/run.go:27 +0x3e fp=0xc00011df70 sp=0xc00011df20 pc=0xdfebde
main.main()
C:/Users/bhper/go/src/github.com/bhperry/space-miner/main.go:117 +0x34 fp=0xc00011df88 sp=0xc00011df70 pc=0xe31274
runtime.main()
c:/go/src/runtime/proc.go:204 +0x209 fp=0xc00011dfe0 sp=0xc00011df88 pc=0xd1ace9
runtime.goexit()
c:/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00011dfe8 sp=0xc00011dfe0 pc=0xd48b41
goroutine 2 [force gc (idle)]:
runtime.gopark(0xed6348, 0xfec9e0, 0x1411, 0x1)
c:/go/src/runtime/proc.go:306 +0xfa fp=0xc000047fb0 sp=0xc000047f90 pc=0xd1b0ba
runtime.goparkunlock(...)
c:/go/src/runtime/proc.go:312
runtime.forcegchelper()
c:/go/src/runtime/proc.go:255 +0xcd fp=0xc000047fe0 sp=0xc000047fb0 pc=0xd1af4d
runtime.goexit()
c:/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000047fe8 sp=0xc000047fe0 pc=0xd48b41
created by runtime.init.6
c:/go/src/runtime/proc.go:243 +0x3c
goroutine 3 [GC sweep wait]:
runtime.gopark(0xed6348, 0xfecac0, 0x140c, 0x1)
c:/go/src/runtime/proc.go:306 +0xfa fp=0xc000049fa8 sp=0xc000049f88 pc=0xd1b0ba
runtime.goparkunlock(...)
c:/go/src/runtime/proc.go:312
runtime.bgsweep(0xc00000c150)
c:/go/src/runtime/mgcsweep.go:163 +0xb2 fp=0xc000049fd8 sp=0xc000049fa8 pc=0xd058b2
runtime.goexit()
c:/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000049fe0 sp=0xc000049fd8 pc=0xd48b41
created by runtime.gcenable
c:/go/src/runtime/mgc.go:217 +0x67
goroutine 4 [GC scavenge wait]:
runtime.gopark(0xed6348, 0xfecbe0, 0x140d, 0x1)
c:/go/src/runtime/proc.go:306 +0xfa fp=0xc000057f78 sp=0xc000057f58 pc=0xd1b0ba
runtime.goparkunlock(...)
c:/go/src/runtime/proc.go:312
runtime.bgscavenge(0xc00000c150)
c:/go/src/runtime/mgcscavenge.go:265 +0xe5 fp=0xc000057fd8 sp=0xc000057f78 pc=0xd03885
runtime.goexit()
c:/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000057fe0 sp=0xc000057fd8 pc=0xd48b41
created by runtime.gcenable
c:/go/src/runtime/mgc.go:218 +0x89
goroutine 5 [finalizer wait]:
runtime.gopark(0xed6348, 0x101f8c8, 0x1ffff1410, 0x1)
c:/go/src/runtime/proc.go:306 +0xfa fp=0xc00004bf58 sp=0xc00004bf38 pc=0xd1b0ba
runtime.goparkunlock(...)
c:/go/src/runtime/proc.go:312
runtime.runfinq()
c:/go/src/runtime/mfinal.go:175 +0xb2 fp=0xc00004bfe0 sp=0xc00004bf58 pc=0xcfa5d2
runtime.goexit()
c:/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00004bfe8 sp=0xc00004bfe0 pc=0xd48b41
created by runtime.createfing
c:/go/src/runtime/mfinal.go:156 +0x68
rax     0x7ffdcdcb0158
rbx     0x7ffdcdcb0156
rcx     0x77
rdi     0xffffffffffbadd11
rsi     0x0
rbp     0x0
rsp     0xba011fedb0
r8      0x97c
r9      0x97c
r10     0x97c
r11     0x97c
r12     0xc000007a
r13     0x0
r14     0x7ffdcdcb0158
r15     0x7ffdd29f0000
rip     0x2003c540000
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
--
```

**Comment by bhperry** [comment]
oh woops, wrong repo. I'll open one on `go-gl/glfw`.

**Comment by elmindreda** [comment]
No worries!
