### ISSUE TITLE
Segfault when running under gnome wayland

### ISSUE THREAD

**Issue by ThomasConrad** [glfw/glfw#2290]
I am trying to run one of the nvidia optix ray-tracing samples and run it using wayland. It runs fine in X11, but when launching with wayland I get a segfault. I do not have much prior experience with glfw and do not know what could cause this. I am using fedora 37 and using gnome. Here is a stack trace of the error:

``` gdb
Thread 1 "render" received signal SIGSEGV, Segmentation fault.
wl_proxy_get_version (proxy=0x0) at ../src/wayland-client.c:2212
2212            return proxy->version;
(gdb) where
#0  wl_proxy_get_version (proxy=0x0) at ../src/wayland-client.c:2212
^[[A#1  0x00007ffff7bd294a in wl_shell_get_shell_surface (wl_shell=0x0, surface=0x43c2ba0) at /usr/include/wayland-client-protocol.h:3032
#2  0x00007ffff7bd3723 in createShellSurface (window=0x43c2820) at /home/user/Documents/Optix_framework/support/GLFW/src/wl_window.c:223
#3  0x00007ffff7bd3b5e in _glfwPlatformCreateWindow (window=0x43c2820, wndconfig=0x7fffffffcc60, ctxconfig=0x7fffffffcc90, fbconfig=0x7fffffffccc0)
    at /home/user/Documents/Optix_framework/support/GLFW/src/wl_window.c:407
#4  0x00007ffff7bce7da in glfwCreateWindow (width=1920, height=1080, title=0x458498 "render_OptiX_user", monitor=0x0, share=0x0)
    at /home/user/Documents/Optix_framework/support/GLFW/src/window.c:196
#5  0x00007ffff7e347ff in sutil::initGLFW (window_title=0x458498 "render_OptiX_user", width=1920, height=1080)
    at /home/user/Documents/Optix_framework/sutil/sutil.cpp:387
#6  0x00007ffff7e34c54 in sutil::initUI (window_title=0x458498 "render_OptiX_user", width=1920, height=1080)
    at /home/user/Documents/Optix_framework/sutil/sutil.cpp:416
#7  0x0000000000422813 in main (argc=1, argv=0x7fffffffd918) at /home/user/Documents/Optix_framework/render/render.cpp:441
```

**Comment by ThomasConrad** [comment]
Turns out i just had to update to the newest version of GLFW installed on my system instead of the one included with the sample. In the end I deleted my GLFW folder and recompiled everything and now it works.
