### ISSUE TITLE
Call to keyboardHandleModifiers() at runtime causes applications to segfault

### ISSUE THREAD

**Issue by quadroli** [glfw/glfw#2329]
OS and version: Alpine Linux 3.17
Release: GLFW 3.3.8
Error messages: None provided by glfwGetError
Desktop Environment: Sway 1.8
Call stack: find attached output by strace

https://user-images.githubusercontent.com/58091631/235137270-9642be13-94ab-4895-af6f-e0a15a8745c0.mp4

[log.txt](https://github.com/glfw/glfw/files/11353076/log.txt)

**Comment by quadroli** [comment]
Further update, restarting sway is actually what seems to fix it, but, it does not get rid of the issue entirely as it is re-occuring.

**Comment by quadroli** [comment]
Further observation: programs do not crush when run under valgrind i.e.: valgrind ./clipboard

**Comment by quadroli** [comment]
However, running them separately afterwards changes cause for segfault eg, clipboard test app now crushes on third Ctrl+c

**Comment by quadroli** [comment]
More information. This is the output of running ```gdb ./a.out ./core```bt having built glfw for wayland in debug mode
```Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f787e4e0c05 in ?? () from /lib/ld-musl-x86_64.so.1
[Current thread is 1 (LWP 11025)]
(gdb) bt
#0  0x00007f787e4e0c05 in ?? () from /lib/ld-musl-x86_64.so.1
#1  0x00007ffc899fde60 in ?? ()
#2  0x0000564537381b19 in keyboardHandleModifiers (userData=0x17970000000000, 
    keyboard=0x78744d6a6f7250, serial=1480192, modsDepressed=0, modsLatched=6648437, 
    modsLocked=1954047316, group=1943812904)
    at /home/mela/glfw_opengl3/glfw-3.3.8/src/wl_window.c:1581```

**Comment by quadroli** [comment]
Update: issue is non-existent on master. 
I feel comfortable closing it now as I am satisfied with that
