### ISSUE TITLE
Implement support for native wayland

### ISSUE THREAD

**Issue by thiloho** [glfw/glfw#2347]
I am not sure how much effort this is, but it would be great if we were able to play games such as Minecraft with native wayland instead of having to rely on xwayland to make the game work.

When I for example try to start Minecraft with sway and native wayland (xwayland disabled via option), the following error appears:
```
GLFW error 65548: Wayland: The platform does not support setting the window icon.
Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).
press enter to continue 
[01:30:17] [Render thread/WARN]: Failed to create window: 
egi$a: GLFW error 65548: Wayland: The platform does not support setting the window icon
	at egi.b(SourceFile:218) ~[minecraft-1.19.4-client.jar:?]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokePPV(Native Method) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.nglfwSetWindowIcon(GLFW.java:2336) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwSetWindowIcon(GLFW.java:2368) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at egi.a(SourceFile:180) ~[minecraft-1.19.4-client.jar:?]
	at emh.<init>(SourceFile:503) ~[minecraft-1.19.4-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:198) ~[minecraft-1.19.4-client.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Process exited with code 0.
```

Some people already created a patch to make Minecraft run on native wayland, it can be found here: https://github.com/Admicos/minecraft-wayland
The problem with this patch is that you explicitly have to apply it, and it only works for the versions below 1.19+, so it is far from ideal. 

I would appreciate if someone who is fairly familiar with the code-base of this project could give an estimation on how much effort or how long it would take to resolve the issue. Having more games that do not require us to use xwayland is a major step forwards, because at this point of time games are the only problem I have when using native wayland.

**Comment by IMS212** [comment]
GLFW does support wayland. The error you are seeing is Minecraft incorrectly assuming it is able to set the window icon on Wayland.

**Comment by thiloho** [comment]
> GLFW does support wayland. The error you are seeing is Minecraft incorrectly assuming it is able to set the window icon on Wayland.

Yes, that was my initial thought as well. I did not really know where I would post this issue, somewhere on [Minecraft Help](https://help.minecraft.net) would probably be my best bet? Unfortunately I could not find an easy fix for this problem, only more complicated workarounds.

**Comment by randomairborne** [comment]
you should make a report on the Minecraft bug tracker, over at https://bugs.mojang.com

**Comment by dougbinks** [comment]
I'm closing this as it is not a GLFW issue.
