### ISSUE TITLE
Crash on Wayland when switching to a virtual console

### ISSUE THREAD

**Issue by danberindei** [glfw/glfw#2492]
Kitty crashes for me every time I use Ctrl+Alt+F3 to switch to a virtual console.

I opened the bug here because AFAICT there is no Kitty code in the stacktrace.

```
#0  0x0000fffed2b51ee4 in wl_proxy_get_version (proxy=proxy@entry=0x0) at ../src/wayland-client.c:2249
#1  0x0000fffed226f86c in wl_pointer_set_cursor (hotspot_y=11, hotspot_x=10, surface=0xaaab3696e880, serial=37982, wl_pointer=0x0) at /usr/include/wayland-client-protocol.h:4967
#2  setCursorImage (window=<optimized out>, on_theme_change=<optimized out>) at glfw/wl_window.c:204
#3  0x0000fffed2275c00 [PAC] in checkScaleChange.part.0.lto_priv.0 (window=0xaaab36b94cb0) at glfw/wl_window.c:244
#4  0x0000fffed2262cb8 [PAC] in checkScaleChange (window=0xaaab36b94cb0) at glfw/wl_window.c:223
#5  surfaceHandleLeave (data=0xaaab36b94cb0, surface=<optimized out>, output=<optimized out>) at glfw/wl_window.c:400
#6  0x0000fffed230c050 [PAC] in ffi_call_SYSV () at ../src/aarch64/sysv.S:127
#7  0x0000fffed23063ac in ffi_call_int (cif=cif@entry=0xffffc1cdaaa8, fn=<optimized out>, orig_rvalue=0xfffed23200f0 <ffi_type_pointer>, orig_rvalue@entry=0x0, avalue=avalue@entry=0xffffc1cdab78, 
    closure=0xfffed23200f0 <ffi_type_pointer>, closure@entry=0x0) at ../src/aarch64/ffi.c:816
#8  0x0000fffed2308a6c [PAC] in ffi_call (cif=cif@entry=0xffffc1cdaaa8, fn=<optimized out>, rvalue=rvalue@entry=0x0, avalue=avalue@entry=0xffffc1cdab78) at ../src/aarch64/ffi.c:825
#9  0x0000fffed2b51a60 in wl_closure_invoke (closure=closure@entry=0xaaab389669a0, target=<optimized out>, target@entry=0xaaab36b99280, opcode=opcode@entry=1, data=<optimized out>, flags=1)
    at ../src/connection.c:1025
#10 0x0000fffed2b523fc [PAC] in dispatch_event (display=0xaaab369753b0, queue=0xaaab369754a0) at ../src/wayland-client.c:1631
#11 0x0000fffed2b52724 [PAC] in dispatch_queue (queue=0xaaab369754a0, display=0xaaab369753b0) at ../src/wayland-client.c:1777
#12 wl_display_dispatch_queue_pending (display=display@entry=0xaaab369753b0, queue=queue@entry=0xaaab369754a0) at ../src/wayland-client.c:2019
#13 0x0000fffed2b5279c [PAC] in wl_display_dispatch_pending (display=display@entry=0xaaab369753b0) at ../src/wayland-client.c:2082
#14 0x0000fffed226585c in handleEvents (timeout=<optimized out>) at glfw/wl_window.c:795
#15 _glfwPlatformWaitEvents () at glfw/wl_window.c:1324
#16 _glfwPlatformRunMainLoop (data=0xfffec53bd0d0, tick_callback=0xfffed36ca300 <process_global_state>) at glfw/main_loop.h:30
#17 glfwRunMainLoop (callback=0xfffed36ca300 <process_global_state>, data=0xfffec53bd0d0) at glfw/init.c:355
#18 0x0000fffed36c32d8 [PAC] in run_main_loop (cb=<optimized out>, cb_data=0xfffec53bd0d0) at kitty/glfw.c:1957
#19 main_loop (self=0xfffec53bd0d0, a=<optimized out>) at kitty/child-monitor.c:1266
```

Running Gnome 45 on Asahi Linux (kernel 6.6.3-413.asahi.fc39.aarch64+16k).

**Comment by elmindreda** [comment]
This is specific to Kitty's fork of GLFW, so you will have to report the bug to them. Very few of the functions in that stack trace even exist in this repository.

**Comment by danberindei** [comment]
Thanks @elmindreda, I'll do that.
