### ISSUE TITLE
glfwInit segfaults on headless weston

### ISSUE THREAD

**Issue by jcowgill** [glfw/glfw#2517]
I tried to run GLFW with Weston in headless mode (I was trying to do this for some CI testing) but it segfaults.

OS and version: Debian unstable
Release or commit: 3.4
Error messages: Nothing is printed

```
$ weston --no-config --backends headless &
[22:33:07.368] weston 13.0.0
               https://wayland.freedesktop.org
               Bug reports to: https://gitlab.freedesktop.org/wayland/weston/issues/
               Build: 13.0.0
[22:33:07.368] Command line: weston --no-config --backends headless
[22:33:07.368] OS: Linux, 6.7.9-amd64, #1 SMP PREEMPT_DYNAMIC Debian 6.7.9-2 (2024-03-13), x86_64
...
$ WAYLAND_DEBUG=client XDG_SESSION_TYPE=wayland WAYLAND_DISPLAY=wayland-1 gdb tests/glfwinfo
...
(gdb) r
[3858817.306]  -> wl_display@1.get_registry(new id wl_registry@2)
[3858817.424]  -> wl_display@1.sync(new id wl_callback@3)
[3858817.603] wl_display@1.delete_id(3)
[3858817.627] wl_registry@2.global(1, "wl_compositor", 5)
[3858817.643]  -> wl_registry@2.bind(1, "wl_compositor", 3, new id [unknown]@4)
[3858817.660] wl_registry@2.global(2, "wl_subcompositor", 1)
[3858817.672]  -> wl_registry@2.bind(2, "wl_subcompositor", 1, new id [unknown]@5)
[3858817.687] wl_registry@2.global(3, "wp_viewporter", 1)
[3858817.704]  -> wl_registry@2.bind(3, "wp_viewporter", 1, new id [unknown]@6)
[3858817.718] wl_registry@2.global(4, "zxdg_output_manager_v1", 2)
[3858817.733] wl_registry@2.global(5, "wp_presentation", 1)
[3858817.746] wl_registry@2.global(6, "wp_single_pixel_buffer_manager_v1", 1)
[3858817.760] wl_registry@2.global(7, "wp_tearing_control_manager_v1", 1)
[3858817.775] wl_registry@2.global(8, "zwp_relative_pointer_manager_v1", 1)
[3858817.789]  -> wl_registry@2.bind(8, "zwp_relative_pointer_manager_v1", 1, new id [unknown]@7)
[3858817.803] wl_registry@2.global(9, "zwp_pointer_constraints_v1", 1)
[3858817.825]  -> wl_registry@2.bind(9, "zwp_pointer_constraints_v1", 1, new id [unknown]@8)
[3858817.839] wl_registry@2.global(10, "zwp_input_timestamps_manager_v1", 1)
[3858817.853] wl_registry@2.global(11, "weston_capture_v1", 1)
[3858817.868] wl_registry@2.global(12, "wl_data_device_manager", 3)
[3858817.882]  -> wl_registry@2.bind(12, "wl_data_device_manager", 1, new id [unknown]@9)
[3858817.896] wl_registry@2.global(13, "wl_shm", 1)
[3858817.911]  -> wl_registry@2.bind(13, "wl_shm", 1, new id [unknown]@10)
[3858817.925] wl_registry@2.global(14, "zwp_linux_explicit_synchronization_v1", 2)
[3858817.939] wl_registry@2.global(15, "wl_output", 4)
[3858817.953]  -> wl_registry@2.bind(15, "wl_output", 4, new id [unknown]@11)
[3858817.972] wl_registry@2.global(16, "zwp_input_panel_v1", 1)
[3858817.985] wl_registry@2.global(17, "zwp_text_input_manager_v1", 1)
[3858818.001] wl_registry@2.global(18, "xdg_wm_base", 5)
[3858818.015]  -> wl_registry@2.bind(18, "xdg_wm_base", 1, new id [unknown]@12)
[3858818.030] wl_registry@2.global(19, "weston_desktop_shell", 1)
[3858818.048] wl_callback@3.done(3)
[3858818.061]  -> wl_display@1.sync(new id wl_callback@3)
[3858818.180] wl_display@1.delete_id(3)
[3858818.193] wl_output@11.geometry(0, 0, 1024, 640, 0, "weston", "headless", 0)
[3858818.211] wl_output@11.scale(1)
[3858818.219] wl_output@11.mode(3, 1024, 640, 60000)
[3858818.232] wl_output@11.name("headless")
[3858818.242] wl_output@11.description("headless")
[3858818.251] wl_output@11.done()
[3858818.260] wl_callback@3.done(3)
[3858818.271]  -> wl_display@1.get_registry(new id wl_registry@3)
[3858818.281]  -> wl_display@1.sync(new id wl_callback@13)
[3858954.559]  -> wl_display@1.get_registry(new id wl_registry@14)
[3858954.577]  -> wl_display@1.sync(new id wl_callback@15)
[3858954.587]  -> wl_display@1.sync(new id wl_callback@16)
[3858954.733] wl_display@1.delete_id(13)
[3858954.744] wl_display@1.delete_id(15)
[3858954.748] wl_display@1.delete_id(16)
[3858954.753] wl_registry@3.global(1, "wl_compositor", 5)
[3858954.759] wl_registry@3.global(2, "wl_subcompositor", 1)
[3858954.764] wl_registry@3.global(3, "wp_viewporter", 1)
[3858954.769] wl_registry@3.global(4, "zxdg_output_manager_v1", 2)
[3858954.773] wl_registry@3.global(5, "wp_presentation", 1)
[3858954.778] wl_registry@3.global(6, "wp_single_pixel_buffer_manager_v1", 1)
[3858954.784] wl_registry@3.global(7, "wp_tearing_control_manager_v1", 1)
[3858954.791] wl_registry@3.global(8, "zwp_relative_pointer_manager_v1", 1)
[3858954.797] wl_registry@3.global(9, "zwp_pointer_constraints_v1", 1)
[3858954.803] wl_registry@3.global(10, "zwp_input_timestamps_manager_v1", 1)
[3858954.808] wl_registry@3.global(11, "weston_capture_v1", 1)
[3858954.814] wl_registry@3.global(12, "wl_data_device_manager", 3)
[3858954.819] wl_registry@3.global(13, "wl_shm", 1)
[3858954.825] wl_registry@3.global(14, "zwp_linux_explicit_synchronization_v1", 2)
[3858954.830] wl_registry@3.global(15, "wl_output", 4)
[3858954.836] wl_registry@3.global(16, "zwp_input_panel_v1", 1)
[3858954.842] wl_registry@3.global(17, "zwp_text_input_manager_v1", 1)
[3858954.847] wl_registry@3.global(18, "xdg_wm_base", 5)
[3858954.854]  -> wl_registry@3.bind(18, "xdg_wm_base", 5, new id [unknown]@17)
[3858954.861] wl_registry@3.global(19, "weston_desktop_shell", 1)
[3858954.867] wl_callback@13.done(3)
[3858954.873] wl_registry@14.global(1, "wl_compositor", 5)
[3858954.880]  -> wl_registry@14.bind(1, "wl_compositor", 4, new id [unknown]@13)
[3858954.887] wl_registry@14.global(2, "wl_subcompositor", 1)
[3858954.893]  -> wl_registry@14.bind(2, "wl_subcompositor", 1, new id [unknown]@18)
[3858954.899] wl_registry@14.global(3, "wp_viewporter", 1)
[3858954.905] wl_registry@14.global(4, "zxdg_output_manager_v1", 2)
[3858954.911] wl_registry@14.global(5, "wp_presentation", 1)
[3858954.916] wl_registry@14.global(6, "wp_single_pixel_buffer_manager_v1", 1)
[3858954.922] wl_registry@14.global(7, "wp_tearing_control_manager_v1", 1)
[3858954.928] wl_registry@14.global(8, "zwp_relative_pointer_manager_v1", 1)
[3858954.934] wl_registry@14.global(9, "zwp_pointer_constraints_v1", 1)
[3858954.940] wl_registry@14.global(10, "zwp_input_timestamps_manager_v1", 1)
[3858954.945] wl_registry@14.global(11, "weston_capture_v1", 1)
[3858954.951] wl_registry@14.global(12, "wl_data_device_manager", 3)
[3858954.957] wl_registry@14.global(13, "wl_shm", 1)
[3858954.963]  -> wl_registry@14.bind(13, "wl_shm", 1, new id [unknown]@19)
[3858954.969]  -> wl_display@1.sync(new id wl_callback@20)
[3858954.975] wl_registry@14.global(14, "zwp_linux_explicit_synchronization_v1", 2)
[3858954.981] wl_registry@14.global(15, "wl_output", 4)
[3858954.987]  -> wl_registry@14.bind(15, "wl_output", 3, new id [unknown]@21)
[3858954.994] wl_registry@14.global(16, "zwp_input_panel_v1", 1)
[3858954.999] wl_registry@14.global(17, "zwp_text_input_manager_v1", 1)
[3858955.005] wl_registry@14.global(18, "xdg_wm_base", 5)
[3858955.011] wl_registry@14.global(19, "weston_desktop_shell", 1)
[3858955.017] wl_callback@15.done(3)
[3858955.022] wl_callback@16.done(3)
[3858955.039]  -> wl_display@1.sync(new id wl_callback@16)

Program received signal SIGSEGV, Segmentation fault.
wl_proxy_get_version (proxy=0x0) at ../src/wayland-client.c:2248
2248	../src/wayland-client.c: No such file or directory.
(gdb) bt
#0  wl_proxy_get_version (proxy=0x0) at ../src/wayland-client.c:2248
#1  0x000055555558ad73 in wl_seat_get_version (wl_seat=0x0) at .../glfw3/build/src/wayland-client-protocol.h:4288
#2  0x000055555558d820 in _glfwInitWayland () at .../glfw3/src/wl_init.c:856
#3  0x000055555556dff6 in glfwInit () at .../glfw3/src/init.c:405
#4  0x000055555556a0be in main (argc=1, argv=0x7fffffffdc28) at .../glfw3/tests/glfwinfo.c:677
```

I'm guessing the `wl_seat=0x0` is the problem.

I found this: https://gitlab.freedesktop.org/wayland/weston/-/merge_requests/209 which suggests weston not registering a `wl_seat` global for the headless backend is intentional.

**Comment by elmindreda** [comment]
Thank you for the bug report! This should be fixed now with 3573c5a890b4878bb7357f71daaf49260c6fef15.
