### ISSUE TITLE
GLFW tests freeze when I hide window in multiscreen applications

### ISSUE THREAD

**Issue by Quark-Hell** [glfw/glfw#2640]
My system:
OS: Arch Linux x86_x64
WM: KWin(Wayland)
CPU: AMD Ryzen 5 2600
GPU: Geforce RTX 3050

What I do:
1) git clone the repo and build project. 
2) run "build/examples/share"
3) hide second window
4) get "Not responding" from first window

Also I can hide one window and other get me not responding if i try maximize it

It's also happen if I run "build/examples/windows"

**Comment by Quark-Hell** [comment]
I trying to add glfwSwapInterval(0); and always work good.

**Comment by elmindreda** [comment]
By hide, do you mean minimize or `glfwHideWindow`?

I tried both and cannot reproduce this on KDE on Wayland. The visible first window remains responsive in both cases here. Which version of KDE are you using?

**Comment by GamesTrap** [comment]
I was able to reproduce this

https://github.com/user-attachments/assets/645f4ea9-729a-4e0e-8d6b-162826975dca

**Comment by Quark-Hell** [comment]
GamesTrap reproduce it behavior.

I think that happen because glfw does not can swap buffer for iconified window. 

I trying checking that window was iconified and skip it, but Wayland does not have that parameter.

**Comment by GamesTrap** [comment]
Can confirm that the second window gets stuck when the first window is iconified because the call to `glfwSwapBuffers()` from the first window never finishes while it is in iconified state.

```c++
#0  0x00007ffff7da163d in poll () from /usr/lib/libc.so.6
#1  0x00007ffff7c8b186 in wl_display_dispatch_queue () from /usr/lib/libwayland-client.so.0
#2  0x00007ffff1342ba1 in ?? () from /usr/lib/libEGL_mesa.so.0
#3  0x00007ffff1339ce7 in ?? () from /usr/lib/libEGL_mesa.so.0
#4  0x00007ffff132dafb in ?? () from /usr/lib/libEGL_mesa.so.0
#5  0x00007ffff1320dc9 in ?? () from /usr/lib/libEGL_mesa.so.0
#6  0x0000555555596688 in swapBuffersEGL (window=0x5555557e9f10) at /home/gamestrap/Downloads/glfw/src/egl_context.c:293
#7  0x0000555555568550 in glfwSwapBuffers (handle=0x5555557e9f10) at /home/gamestrap/Downloads/glfw/src/context.c:662
#8  0x00005555555673b3 in main (argc=1, argv=0x7fffffffe1a8) at /home/gamestrap/Downloads/glfw/examples/sharing.c:225
```

**Comment by elmindreda** [comment]
The [wayland-surface-frame](https://github.com/glfw/glfw/tree/wayland-surface-frame) branch is in testing and should hopefully resolve this issue. Testing and other feedback is very welcome.
