### ISSUE TITLE
Deadlock with AMD libGL attempting to lock display during XSync

### ISSUE THREAD

**Issue by capnm** [glfw/glfw#283]
I found that by an accident during debugging (was wondering why my app deadlogs).

```
cd tests
./glfwinfo  -m 4 -n 4 or -m 5, etc.
```

```
gdb ./glfwinfo
r -m 4 -n 4
ctrl+c
LFW library version string: "3.1.0 X11 GLX glXGetProcAddress clock_gettime /dev/js"
^C
Program received signal SIGINT, Interrupt.
__lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
135 ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S

bt
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffff788d17c in _L_lock_982 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007ffff788cfcb in __GI___pthread_mutex_lock (mutex=0x422350) at pthread_mutex_lock.c:64
#3  0x00007ffff7ad0e43 in _XLockDisplay (dpy=0x41b3b0) at ../../src/locking.c:459
#4  0x00007ffff7aded39 in XSync (dpy=0x41b3b0, discard=0) at ../../src/Sync.c:42
#5  0x000000000040d3a5 in _glfwReleaseXErrorHandler ()
#6  0x0000000000412921 in _glfwCreateContext ()
#7  0x00000000004104bd in _glfwPlatformCreateWindow ()
#8  0x000000000040a33b in glfwCreateWindow ()
#9  0x0000000000406833 in main ()
```

**Comment by elmindreda** [comment]
Just a heads-up; that bug report will be closed as wontfix a week from now.

**Comment by capnm** [comment]
Still broken with the latest ubuntu 15.200 AMD driver.

./glfwinfo  -m 4
```
GLFW header version: 3.1.2
GLFW library version: 3.1.2
GLFW library version string: "3.1.2 X11 GLX clock_gettime /dev/js"
OpenGL context version string: "4.0.13374 Core Profile Context 14.20"
OpenGL context version parsed by GLFW: 4.0.13374
OpenGL context flags (0x00000000):
OpenGL context flags parsed by GLFW:
OpenGL profile mask (0x00000001): core
OpenGL profile mask parsed by GLFW: core
OpenGL context renderer string: "AMD Radeon HD 7700 Series  "
OpenGL context vendor string: "ATI Technologies Inc."
OpenGL context shading language version: "4.40"
Framebuffer:
 red: 8 green: 8 blue: 8 alpha: 8 depth: 24 stencil: 8
 samples: 0 sample buffers: 0
```

./glfwinfo  -m 5
```
GLFW header version: 3.1.2
GLFW library version: 3.1.2
GLFW library version string: "3.1.2 X11 GLX clock_gettime /dev/js"
--deadlock--
```

**Comment by elmindreda** [comment]
I'm subscribed to their tracker entry. Hope something happens this time around.

**Comment by capnm** [comment]
The catalyst driver with this bug is outdated and I don't use the closed source drives any more.
Mesa works fine... closing.

**Comment by elmindreda** [comment]
Thank you for the follow-up!
